#################################
#                               #
# Skies main configuration file #
#                               #
#################################

# Meta information
meta:

    # Title of the website
    title: Skies

# Subdirectory on the webserver
# Example: 'http://test.skies.net/Skies/' is the Skies URL. In this case, 'Skies/' is the subdir
subdir: 'Skies/'

# Default language
defaultLanguage: de-DE

# Default style (short name)
defaultStyle: woobie

# Default page (Homepage)
defaultPage: home

# Default time zone
defaultTimezone: Europe/Berlin

# Are normal users allowed to login?
allowNormalLogin: true
